# Generated by Django 5.2.4 on 2026-03-15 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('pickup_location', models.CharField(max_length=500)),
                ('destination', models.CharField(max_length=500)),
                ('requested_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('completed', 'Completed')], default='pending', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=200)),
                ('current_location', models.CharField(max_length=500)),
                ('available_from', models.DateTimeField()),
                ('available_until', models.DateTimeField()),
                ('status', models.CharField(default='available', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='agents.riderequest')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='agents.volunteeravailability')),
            ],
        ),
    ]
