# Generated by Django 5.2.4 on 2025-10-04 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stransport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportassignment',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transportassignment',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transportassignment', to='stransport.transportrequest'),
        ),
    ]
