# Generated by Django 5.2.4 on 2025-10-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stransport', '0002_transportassignment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
