# Generated by Django 5.2.4 on 2025-10-07 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stransport', '0003_transportrequest_number_of_people_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportrequest',
            name='number_of_people',
        ),
        migrations.RemoveField(
            model_name='transportrequest',
            name='phone',
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='no_volunteers_available',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TransportRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='stransport.transportrequest')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('request', 'volunteer')},
            },
        ),
    ]
