# Generated by Django 5.2.4 on 2026-02-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stransport', '0007_transportrequest_ai_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('sick', 'מטופל'), ('volunteer', 'מתנדב')], max_length=20),
        ),
    ]
