# Generated by Django 5.2.4 on 2026-03-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stransport', '0009_volunteerlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='מועד הביטול – בקשה מבוטלת מוצגת עד למחרת', null=True),
        ),
    ]
