# Generated by Django 5.2.4 on 2026-03-14 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stransport', '0010_add_cancelled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='תיאור חופשי של הנסיעה המתוכננת')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'פתוח'), ('matched', 'הותאם'), ('cancelled', 'בוטל')], default='open', max_length=20)),
                ('parsed_date', models.DateField(blank=True, null=True)),
                ('parsed_time', models.TimeField(blank=True, null=True)),
                ('parsed_from', models.CharField(blank=True, max_length=255)),
                ('parsed_to', models.CharField(blank=True, max_length=255)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
